# Generated by Django 2.1.7 on 2019-03-04 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cataloghistory',
            name='backend_array_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cataloghistory',
            name='backend_storagepool_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cataloghistory',
            name='hlu_on_vplex',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cataloghistory',
            name='lun_name_on_backend',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cataloghistory',
            name='lun_size',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cataloghistory',
            name='primary_mds_switch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cataloghistory',
            name='secondary_mds_switch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cataloghistory',
            name='server_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='cataloghistory',
            name='thin_volume_or_not',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cataloghistory',
            name='vplex_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cataloghistory',
            name='wwpn_1',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='cataloghistory',
            name='wwpn_2',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='cataloghistory',
            name='message',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cataloghistory',
            name='register_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
